monolog:
    handlers:
        main:
            type: fingers_crossed # Activera le handler lié que si le niveau configuré est atteint
            # Ici, lorsque "error" sera atteint, toutes les erreurs > à "debug" seront logguées via "nested"
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
